spring:
  application:
    name: plant-service
  profiles:
    active: k8
  jackson:
    default-property-inclusion: non_empty

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: full
        retryer:
          period: 100
          maxPeriod: 1000
          maxAttempts: 3

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
