spring:
  application:
    name: plant-service

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: full
        retryer:
          period: 100
          maxPeriod: 1000
          maxAttempts: 3

care-tip-service:
  url: http://care-tip-service
